apps/urls.py
from django.urls import path
from . import views

app_name = 'apps'
urlpatterns = [
    path('throw/', views.throw, name='throw'),
    path('catch/', views.catch, name='catch'),
    path('lotto_create/', views.lotto_create, name='lotto_create'),
    path('lotto/', views.lotto, name='lotto'),
    path('apps/<int:num>/', views.detail, name='detail'),
    path('apps/<str:name>/', views.greeting, name='greeting'),
    path('todaydinner/', views.todaydinner, name='todaydinner'),
]

firstpjt/urls.py
from django.contrib import admin
from django.urls import path, include
# WARNINGS: (urls.W005) URL namespace 'MayTwentyThird' isn't unique. You may not be able to reverse all URLs in this namespace
# https://comdoc.tistory.com/entry/URL-namespace-xxx-isnt-unique
from django.shortcuts import redirect
from django.conf import settings
from django.conf.urls.static import static

urlpatterns = [
    path('', include('mainpg.urls')),
    path('admin/', admin.site.urls),
    path('apps/', include('apps.urls')),
    path('MarchTwentyThird/', include('MarchTwentyThird.urls')),
    path('articles/', include('articles.urls')),
    path('todos/', include('todos.urls')),
    path('accountbooks/', include('accountbooks.urls')),
    path('accounts/', include('accounts.urls')),
    path('albums/', include('albums.urls')),
    path('reviews/', include('reviews.urls')),
    path('hospitals/', include('hospitals.urls')),
    path('__debug__/', include('debug_toolbar.urls')),
] + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

reviews/urls.py
from django.urls import path
from . import views

app_name = 'reviews'
urlpatterns = [
    path('', views.index, name='index'),
    path('<int:review_pk>/', views.detail, name='detail'),
    path('create/', views.create, name='create'),
    path('<int:review_pk>/update/', views.update, name='update'),
    path('<int:review_pk>/delete/', views.delete, name='delete'),
    path('<int:review_pk>/comments/', views.comments_create, name='comments_create'),
    path('<int:review_pk>/comments/<int:comment_pk>/delete/', views.comments_delete, name='comments_delete')
]

reviews/models.py
from django.conf import settings
from django.db import models

# Create your models here.
class Review(models.Model):
    user = models.ForeignKey(settings.AUTH_USER_MODEL, on_delete=models.CASCADE)
    title = models.CharField(max_length=30)
    content = models.CharField(max_length=200)
    movie = models.CharField(max_length=30)
    image = models.ImageField(blank=True, upload_to='')

class Comment(models.Model):
    review = models.ForeignKey(Review, on_delete=models.CASCADE)
    user = models.ForeignKey(settings.AUTH_USER_MODEL, on_delete=models.CASCADE, related_name='reviews_comment')
    content = models.CharField(max_length=200)

reviews/forms.py
from django import forms
from .models import Review, Comment

class ReviewForm(forms.ModelForm):
    title = forms.CharField(
        label="리뷰 제목",
        widget=forms.TextInput(attrs={
            "placeholder": "리뷰 제목을 입력하세요"
        }),
    )
    content = forms.CharField(
        label="리뷰 내용",
        widget=forms.Textarea(attrs={
            "placeholder": "리뷰 내용을 입력하세요"
        }),
    )
    movie = forms.CharField(
        label="영화 제목",
        widget=forms.TextInput(attrs={
            "placeholder": "영화 제목을 입력하세요"
        }),
    )
    image = forms.ImageField(
        label="관련 이미지",
        widget=forms.FileInput(attrs={
            "placeholder": "관련 이미지를 업로드하세요"
        })
    )
    class Meta():
        model = Review
        fields = ('title', 'content', 'movie', 'image')

class CommentForm(forms.ModelForm):
    content = forms.CharField(
        label="새 댓글",
        widget=forms.TextInput(attrs={
            "type": "text",
            "class": "form-control",
            "placeholder": "새로운 댓글을 입력하세요",
            "aria-label": "새로운 댓글을 입력하세요",
            "aria-describedby": "basic-addon2",
        }),
    )
    class Meta():
        model = Comment
        fields = ('content', )

reviews/views.py
from django.shortcuts import render, redirect
from .models import Review, Comment
from .forms import ReviewForm, CommentForm
from django.contrib.auth.decorators import login_required

# Create your views here.
def index(request):
    reviews = Review.objects.all()
    context = {
        'reviews': reviews,
    }
    return render(request, 'reviews/index.html', context)

def detail(request, review_pk):
    review = Review.objects.get(pk=review_pk)
    comments = review.comment_set.all()
    comment_form = CommentForm()
    context = {
        'review': review,
        'comments': comments,
        'comment_form': comment_form,
    }
    return render(request, 'reviews/detail.html', context)

@login_required
def comments_create(request, review_pk):
    review = Review.objects.get(pk=review_pk)
    comment_form = CommentForm(request.POST)
    if comment_form.is_valid():
        comment = comment_form.save(commit=False)
        comment.review = review
        comment.user = request.user
        comment_form.save()
        return redirect('reviews:detail', review.pk)
    context = {
        'review': review,
        'comment_form': comment_form,
    }
    return render(request, 'reviews/detail.html', context)

@login_required
def comments_delete(request, review_pk, comment_pk):
    comment = Comment.objects.get(pk=comment_pk)
    if request.user == comment.user:
        comment.delete()
    return redirect('reviews:detail', review_pk)

@login_required
def create(request):
    if request.method == 'POST':
        review_form = ReviewForm(request.POST, request.FILES)
        if review_form.is_valid():
            review = review_form.save(commit=False)
            review.user = request.user
            review.save()
            return redirect('reviews:index')
    else:
        review_form = ReviewForm()
    context = {
        'review_form': review_form,
    }
    return render(request, 'reviews/create.html', context)

@login_required
def update(request, review_pk):
    review = Review.objects.get(pk=review_pk)
    if request.user == review.user:
        if request.method == "POST":
            review_form = ReviewForm(request.POST, request.FILES, instance=review)
            if review_form.is_valid():
                review_form.save()
                return redirect('reviews:detail', review.pk)
        else:
            review_form = ReviewForm(instance=review)
    else:
        return redirect('reviews:index')
    context = {
        'review': review,
        'review_form': review_form,
    }
    return render(request, 'reviews/update.html', context)

@login_required
def delete(request, review_pk):
    review = Review.objects.get(pk=review_pk)
    if request.user == review.user:
        review.delete()
    return redirect('reviews:index')

reviews/templates/reviews/create.html
{% extends 'base.html' %}
{% block style %}
  <style>
    body {
      margin: 20px;
    }
  </style>
{% endblock style %}
{% block content %}
{% load bootstrap5 %}
  <h1>reviews CREATE</h1>
  <hr>
  <form action="{% url 'reviews:create' %}" method="POST" enctype="multipart/form-data">
    {% csrf_token %}
    {% bootstrap_form review_form %}
    <input type="submit" class="btn btn-secondary mb-2">
  </form>
  <a href="{% url 'reviews:index' %}" class="btn btn-secondary">BACK</a>
{% endblock content %}

reviews/templates/reviews/detail.html
{% extends 'base.html' %}
{% block style %}
  <style>
    body {
      margin: 20px;
    }
  </style>
{% endblock style %}
{% block content %}
{% load static %}
  <h1>reviews DETAIL</h1>
  <hr>
  <div class="card">
    <div class="row no-gutters">
      <div class="col-3">
        <img class="card-img-top" src="{{ review.image.url }}" alt="Card image cap">
      </div>
      <div class="col-9">
        <div class="card-body">
          <h4 class="card-title fw-bold">{{ review.movie }} : {{ review.title }}</h4>
          <p class="card-text">{{ review.content }}</p>
          <p class="card-text text-end">(작성자 : {{ review.user }})</p>
        </div>
        <hr>
        <ul class="list-group list-group-flush">
          {% for comment in comments %}
          <li class="list-group-item">
            <div class="row">
              <div class="col-11">
                <p>댓글 {{ comment.pk }} : {{ comment.content }} (작성자 : {{ comment.user }})</p>
              </div>
              {% if comment.user == request.user %}
              <div class="col text-end">
                <form action="{% url 'reviews:comments_delete' review.pk comment.pk %}" method="POST">
                  {% csrf_token %}
                  <input type="submit" value="" class="btn-close"> 
                </form>
              </div>
              {% endif %}
            </div>
          </li>
          {% endfor %}
        </ul>
        <hr>
        <div class="card-body">
          <form action="{% url 'reviews:comments_create' review.pk %}" method="POST">
            {% csrf_token %}
            {{ comment_form.as_p }}
            <div class="input-group-append">
              <input class="btn btn-outline-secondary" type="submit">
            </div>
          </form>
        </div>
        <hr>
        <div class="card-body">
          {% if request.user == review.user %}
          <div class="row">
              <div class="col-4">
                <form action="{% url 'reviews:delete' review.pk %}" method="POST">
                  {% csrf_token %}
                  <input type="submit" value="DELETE" class="btn btn-dark mb-3 form-control">
                </form>
              </div>
              
              <div class="col-4">
                <form action="{% url 'reviews:update' review.pk %}" method="POST">
                  {% csrf_token %}
                  <input type="submit" value="UPDATE" class="btn btn-dark mb-3 form-control">
                </form>
              </div>
            <div class="col-4">
          {% endif %}
              <a href="{% url 'reviews:index' %}" class="btn btn-dark mb-3 form-control">BACK</a>
            </div>
          </div>
        </div>
      </div>
    </div>
  </div>
  {% comment %} <hr>
  <ul>
    <li>
      <img src="{{ review.image.url }}" alt="img">
    </li>
    <li>리뷰 제목 : {{ review.title }}</li>
    <li>리뷰 내용 : {{ review.content }}</li>
    <li>영화 제목 : {{ review.movie }}</li>
    {% for comment in comments %}
    <li>댓글 {{comment.pk }} : {{ comment.content }}
      <form action="{% url 'reviews:comments_delete' review.pk comment.pk %}" method="POST">
        {% csrf_token %}
        <input type="submit" value="DELETE" class="btn btn-dark"> 
      </form>
    </li>
    {% endfor %}
  </ul>
  <hr> {% endcomment %}

  
{% endblock content %}

reviews/templates/reviews/index.html
{% extends 'base.html' %}
{% block style %}
  <style>
    body {
      margin: 20px;
    }
  </style>
{% endblock style %}
{% block content %}
<h1>reviews INDEX</h1>
<hr>
<div class="card mb-2">
  <div class="card-header">
    0. <a href="{% url 'reviews:create' %}">NEW</a>
  </div>
  <div class="card-body">
    <blockquote class="blockquote mb-0">
      <p>새로운 영화 리뷰를 업로드하세요.</p>
    </blockquote>
  </div>
</div>
{% for review in reviews %}
<div class="card mb-2">
  <div class="card-header">
    {{review.pk}}. <a href="{% url 'reviews:detail' review.pk %}">{{ review.title }}</a>
    {{ review.comment_set.count }} (작성자 : {{ review.user }})
  </div>
  <div class="card-body">
    <blockquote class="blockquote mb-0">
      <p>{{ review.content }}</p>
      <footer class="blockquote-footer"><cite title="Source Title">{{ review.movie }}</cite></footer>
    </blockquote>
  </div>
</div>
{% endfor %}
{% endblock content %}

reviews/templates/reviews/update.html
{% extends 'base.html' %}
{% block style %}
  <style>
    body {
      margin: 20px;
    }
  </style>
{% endblock style %}
{% block content %}
{% load bootstrap5 %}
  <h1>reviews CREATE</h1>
  <hr>
  <form action="{% url 'reviews:update' review.pk %}" method="POST" enctype="multipart/form-data">
    {% csrf_token %}
    {% bootstrap_form review_form %}
    <input type="submit" class="btn btn-secondary mb-2">
  </form>
  <a href="{% url 'reviews:index' %}" class="btn btn-secondary">BACK</a>
{% endblock content %}