accounts/urls.py
from django.urls import path
from . import views

app_name = 'accounts'
urlpatterns = [
    path('login/', views.login, name='login'),
    path('logout/', views.logout, name='logout'),
    path('signup/', views.signup, name='signup'),
    path('delete/', views.delete, name='delete'),
    path('update/', views.update, name='update'),
    path('password/', views.change_password, name='change_password'),
    path('profile/<username>/', views.profile, name='profile'),
    path('<int:user_pk>/follow/', views.follow, name='follow'),
]

albums/urls.py
from django.urls import path
from . import views


app_name = 'albums'
urlpatterns = [
    path('', views.index, name='index'),
    path('create/', views.create, name='create')
]

apps/urls.py
from django.urls import path
from . import views

app_name = 'apps'
urlpatterns = [
    path('throw/', views.throw, name='throw'),
    path('catch/', views.catch, name='catch'),
    path('lotto_create/', views.lotto_create, name='lotto_create'),
    path('lotto/', views.lotto, name='lotto'),
    path('apps/<int:num>/', views.detail, name='detail'),
    path('apps/<str:name>/', views.greeting, name='greeting'),
    path('todaydinner/', views.todaydinner, name='todaydinner'),
]

firstpjt/urls.py
from django.contrib import admin
from django.urls import path, include
# WARNINGS: (urls.W005) URL namespace 'MayTwentyThird' isn't unique. You may not be able to reverse all URLs in this namespace
# https://comdoc.tistory.com/entry/URL-namespace-xxx-isnt-unique
from django.shortcuts import redirect
from django.conf import settings
from django.conf.urls.static import static

urlpatterns = [
    path('', include('mainpg.urls')),
    path('admin/', admin.site.urls),
    path('apps/', include('apps.urls')),
    path('MarchTwentyThird/', include('MarchTwentyThird.urls')),
    path('articles/', include('articles.urls')),
    path('todos/', include('todos.urls')),
    path('accountbooks/', include('accountbooks.urls')),
    path('accounts/', include('accounts.urls')),
    path('albums/', include('albums.urls')),
    path('reviews/', include('reviews.urls')),
    path('hospitals/', include('hospitals.urls')),
    path('__debug__/', include('debug_toolbar.urls')),
] + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

mainpg/urls.py
from django.urls import path
from . import views

app_name = 'mainpg'
urlpatterns = [
    path('', views.index, name='index')
]

reviews/urls.py
from django.urls import path
from . import views

app_name = 'reviews'
urlpatterns = [
    path('', views.index, name='index'),
    path('<int:review_pk>/', views.detail, name='detail'),
    path('create/', views.create, name='create'),
    path('<int:review_pk>/update/', views.update, name='update'),
    path('<int:review_pk>/delete/', views.delete, name='delete'),
    path('<int:review_pk>/comments/', views.comments_create, name='comments_create'),
    path('<int:review_pk>/comments/<int:comment_pk>/delete/', views.comments_delete, name='comments_delete')
]

todos/urls.py
# articles/urls.py

from django.urls import path
from . import views

app_name = 'todos'
urlpatterns = [
    path('', views.index, name='index'),
    path('<int:pk>', views.detail, name='detail'),
    path('create/', views.create, name='create'),
    path('<int:todo_pk>/delete/', views.delete, name='delete'),
    path('<int:todo_pk>/update/', views.update, name='update'),
    path('<int:todo_pk>/check/', views.check, name='check'),
]

mainpg/models.py
from django.db import models

# Create your models here.

mainpg/views.py
from django.shortcuts import render

# Create your views here.
def index(request):
    return render(request, 'mainpg/index.html')

mainpg/templates/mainpg/index.html
{% extends 'base.html' %}

{% block style %}
  <style>
    body {
      margin: 5rem;
    }
  </style>
{% endblock style %}

{% block content %}
{% load bootstrap5 %}
  <h1>INDEX</h1>
  <hr>

  {% if request.user.is_authenticated %}
    <h2 class="mb-5">Hello, {{ user }}</h2>

    <div class="row">
      <a href="{% url 'accountbooks:index' %}" class="btn border-dark mb-3">accountbooks</a>
      <a href="{% url 'accounts:login' %}" class="btn border-dark mb-3">accounts</a>
      <a href="{% url 'albums:index' %}" class="btn border-dark mb-3">albums</a>
      <a href="{% url 'apps:throw' %}" class="btn border-dark mb-3">apps</a>
      <a href="{% url 'articles:index' %}" class="btn border-dark mb-3">articles</a>
      <a href="{% url 'MarchTwentyThird:inpt' %}" class="btn border-dark mb-3">MarchTwentyThird</a>
      <a href="{% url 'reviews:index' %}" class="btn border-dark mb-3">reviews</a>
      <a href="{% url 'todos:index' %}" class="btn border-dark mb-3">todos</a>
      <a href="{% url 'accounts:update' %}" class="btn btn-dark mb-3">update</a>
      <form action="{% url 'accounts:logout' %}" method="POST">
        {% csrf_token %}
        <input type="submit" value="logout" class="btn btn-dark mb-3 form-control">
      </form>
      <form action="{% url 'accounts:delete' %}" method="POST">
        {% csrf_token %}
        <input type="submit" value="delete" class="btn btn-dark mb-3 form-control">
      </form>
    </div>
  {% else %}
    <h2 class="mb-5">Hello, {{ user }}</h2>

    <div class="row">
      <a href="{% url 'accounts:login' %}" class="btn btn-dark mb-3">login</a>
      <a href="{% url 'accounts:signup' %}" class="btn btn-dark mb-3">signup</a>
    </div>
  {% endif %}

{% endblock content %}