accountbooks/urls.py
from django.urls import path
from . import views

app_name = 'accountbooks'
urlpatterns = [
    path('', views.index, name='index'),
    path('<int:accountbook_pk>/', views.detail, name='detail'),
    path('new/', views.new, name='new'),
    path('create/', views.create, name='create'),
    path('<int:accountbook_pk>/edit/', views.edit, name='edit'),
    path('<int:accountbook_pk>/update/', views.update, name='update'),
    path('<int:accountbook_pk>/delete/', views.delete, name='delete'),
    path('<int:accountbook_pk>/copy/', views.copy, name='copy')
]

apps/urls.py
from django.urls import path
from . import views

app_name = 'apps'
urlpatterns = [
    path('throw/', views.throw, name='throw'),
    path('catch/', views.catch, name='catch'),
    path('lotto_create/', views.lotto_create, name='lotto_create'),
    path('lotto/', views.lotto, name='lotto'),
    path('apps/<int:num>/', views.detail, name='detail'),
    path('apps/<str:name>/', views.greeting, name='greeting'),
    path('todaydinner/', views.todaydinner, name='todaydinner'),
]

firstpjt/urls.py
from django.contrib import admin
from django.urls import path, include
# WARNINGS: (urls.W005) URL namespace 'MayTwentyThird' isn't unique. You may not be able to reverse all URLs in this namespace
# https://comdoc.tistory.com/entry/URL-namespace-xxx-isnt-unique
from django.shortcuts import redirect
from django.conf import settings
from django.conf.urls.static import static

urlpatterns = [
    path('', include('mainpg.urls')),
    path('admin/', admin.site.urls),
    path('apps/', include('apps.urls')),
    path('MarchTwentyThird/', include('MarchTwentyThird.urls')),
    path('articles/', include('articles.urls')),
    path('todos/', include('todos.urls')),
    path('accountbooks/', include('accountbooks.urls')),
    path('accounts/', include('accounts.urls')),
    path('albums/', include('albums.urls')),
    path('reviews/', include('reviews.urls')),
    path('hospitals/', include('hospitals.urls')),
    path('__debug__/', include('debug_toolbar.urls')),
] + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

accountbooks/models.py
from django.db import models

# Create your models here.
class AccountBook(models.Model):
    note = models.CharField(max_length=80)
    description = models.TextField(null=True)
    category = models.CharField(max_length=20)
    amount = models.IntegerField(default=0)
    date = models.DateField()
    created_at = models.DateTimeField(auto_now_add=True)
    updated_at = models.DateTimeField(auto_now=True)

accountbooks/views.py
from django.shortcuts import render, redirect
from .models import AccountBook
from datetime import date

# Create your views here.
def index(request):
    accountbooks = AccountBook.objects.all()
    context = {
        'accountbooks': accountbooks,
    }
    return render(request, 'accountbooks/index.html', context)

def detail(request, accountbook_pk):
    accountbook = AccountBook.objects.get(pk=accountbook_pk)
    context = {
        'accountbook': accountbook,
    }
    return render(request, 'accountbooks/detail.html', context)

def new(request):
    cur_date = date.today()
    context = {
        'cur_date': cur_date
    }
    return render(request, 'accountbooks/new.html', context)

def create(request):
    note = request.POST.get('note')
    description = request.POST.get('description')
    category = request.POST.get('category')
    amount = request.POST.get('amount')
    date = request.POST.get('date')
    accountbook = AccountBook(note=note, description=description, category=category, amount=amount, date=date)
    accountbook.save()
    context = {
        'note': note,
        'description': description,
        'category': category,
        'amount': amount,
        'date': date,
    }
    return redirect('accountbooks:detail', accountbook.pk)

def edit(request, accountbook_pk):
    accountbook = AccountBook.objects.get(pk=accountbook_pk)
    context = {
        'accountbook': accountbook,
    }
    return render(request, 'accountbooks/edit.html', context)

def update(request, accountbook_pk):
    accountbook = AccountBook.objects.get(pk=accountbook_pk)
    accountbook.note = request.POST.get('note')
    accountbook.description = request.POST.get('description')
    accountbook.category = request.POST.get('category')
    accountbook.amount = request.POST.get('amount')
    accountbook.date = request.POST.get('date')
    accountbook.save()
    return redirect('accountbooks:detail', accountbook.pk)

def delete(request, accountbook_pk):
    accountbook = AccountBook.objects.get(pk=accountbook_pk)
    accountbook.delete()
    return redirect('accountbooks:index')

def copy(request, accountbook_pk):
    accountbook = AccountBook.objects.get(pk=accountbook_pk)
    newaccntbk = AccountBook(note=accountbook.note, description=accountbook.description, category=accountbook.category, amount=accountbook.amount, date=accountbook.date)
    newaccntbk.save()
    return redirect('accountbooks:detail', newaccntbk.pk)

accountbooks/templates/accountbooks/detail.html
{% extends 'base.html' %}

{% block style %}
  <style>
    body {
      margin: 5rem;
    }
  </style>
{% endblock style %}

{% block content %}
  <h1>AccountBooks DETAIL</h1>
  <hr>

  <div class="card border-dark" style="margin-bottom: 1rem;">
    <div class="card-header">
      {{ accountbook.pk }}. {{ accountbook.note }}</a>
    </div>
    <ul class="list-group list-group-flush">
      <li class="list-group-item">사용 내역 메모: {{ accountbook.description }}</li>
      <li class="list-group-item">사용 내역 분류: {{ accountbook.category }}</li>
      <li class="list-group-item">사용 금액: {{ accountbook.amount }}</li>
      <li class="list-group-item">사용 날짜: {{ accountbook.date }}</li>
    </ul>
  </div>

  <div>
    <div class="row">
      <div class="col">
        <form action="{% url 'accountbooks:copy' accountbook.pk %}" method="POST">
          {% csrf_token %}
          <div class="d-grid">
            <input class="btn bg-dark text-white" type="submit" value="COPY">
          </div>
        </form>
      </div>
      <div class="col">
        <form action="{% url 'accountbooks:delete' accountbook.pk %}" method="POST">
          {% csrf_token %}
          <div class="d-grid">
            <input class="btn border-dark" type="submit" value="DELETE">
          </div>
        </form>
      </div>
      <div class="col">
        <div class="d-grid">
          <a href="{%url 'accountbooks:edit' accountbook.pk %}" class="btn border-dark">EDIT</a>
        </div>
      </div>
      <div class="col">
        <div class="d-grid">
          <a href="{%url 'accountbooks:index'%}" class="btn border-dark">BACK</a>
        </div>
      </div>
    </div>
  </div>
{% endblock content %}

accountbooks/templates/accountbooks/edit.html
{% extends 'base.html' %}

{% block style %}
  <style>
    body {
      margin: 5rem;
    }
  </style>
{% endblock style %}

{% block content %}
  <h1>AccountBooks EDIT</h1>
  <hr>

  <form action="{% url 'accountbooks:update' accountbook.pk %}" method="POST">
    {% csrf_token %}
    <div class="input-group flex-nowrap mb-3">
      <span class="input-group-text" style="width:8rem;" id="addon-wrapping">사용 내역</span>
      <input type="text" id="note" name="note" class="form-control" placeholder="note" aria-label="note" aria-describedby="addon-wrapping" value="{{ accountbook.note }}">
    </div>
    <div class="input-group flex-nowrap mb-3">
      <span class="input-group-text" style="width:8rem;" id="addon-wrapping">사용 내역 메모</span>
      <input type="textarea" id="description" name="description" class="form-control" placeholder="description" aria-label="description" aria-describedby="addon-wrapping" value="{{ accountbook.description }}">
    </div>
    <div class="input-group flex-nowrap mb-3">
      <span class="input-group-text" style="width:8rem;" id="addon-wrapping">사용 내역 분류</span>
      <input type="text" id="category" name="category" class="form-control" placeholder="category" aria-label="category" aria-describedby="addon-wrapping" value="{{ accountbook.category }}">
    </div>
    <div class="input-group flex-nowrap mb-3">
      <span class="input-group-text" style="width:8rem;" id="addon-wrapping">사용 금액</span>
      <input type="number" id="amount" name="amount" class="form-control" placeholder="amount" aria-label="amount" aria-describedby="addon-wrapping" value="{{ accountbook.amount }}">
    </div>
    <div class="input-group flex-nowrap mb-3">
      <span class="input-group-text" style="width:8rem;" id="addon-wrapping">사용 날짜</span>
      <input type="date" id="date" name="date" class="form-control" placeholder="date" aria-label="date" aria-describedby="addon-wrapping" value="{{ accountbook.date }}">
    </div>
    <div class="input-group flex-nowrap">
      <input type="submit" class="form-control border-dark" placeholder="SUBMIT" aria-label="SUBMIT" aria-describedby="addon-wrapping">
    </div>
  </form>
{% endblock content %}

accountbooks/templates/accountbooks/index.html
{% extends 'base.html' %}

{% block style %}
  <style>
    body {
      margin: 5rem;
    }
  </style>
{% endblock style %}

{% block content %}
  <h1>AccountBooks INDEX</h1>
  <hr>

  <div class="card border-dark" style="margin-bottom: 1rem;">
    <div class="card-header">
      0. <a href="{%url 'accountbooks:new'%}">NEW</a>
    </div>
    <ul class="list-group list-group-flush">
      <li class="list-group-item">새로운 사용 내역을 추가하세요.</li>
    </ul>
    {% for accountbook_pk in accountbooks %}
    <div class="card-header">
      {{ accountbook_pk.pk }}. <a href="{% url 'accountbooks:detail' accountbook_pk.pk %}">{{ accountbook_pk.note }}</a>
    </div>
    <ul class="list-group list-group-flush">
      <li class="list-group-item">사용 금액: {{ accountbook_pk.amount }}</li>
      <li class="list-group-item">사용 날짜: {{ accountbook_pk.date }}</li>
    </ul>
    {% endfor %}
  </div>
{% endblock content %}

accountbooks/templates/accountbooks/new.html
{% extends 'base.html' %}

{% block style %}
  <style>
    body {
      margin: 5rem;
    }
  </style>
{% endblock style %}

{% block content %}
  <h1>AccountBooks NEW</h1>
  <hr>

  <form action="{%url 'accountbooks:create' %}" method="POST">
    {% csrf_token %}
    <div class="input-group flex-nowrap mb-3">
      <span class="input-group-text" style="width:8rem;" id="addon-wrapping">사용 내역</span>
      <input type="text" id="note" name="note" class="form-control" placeholder="note" aria-label="note" aria-describedby="addon-wrapping">
    </div>
    <div class="input-group flex-nowrap mb-3">
      <span class="input-group-text" style="width:8rem;" id="addon-wrapping">사용 내역 메모</span>
      <input type="textarea" id="description" name="description" class="form-control" placeholder="description" aria-label="description" aria-describedby="addon-wrapping">
    </div>
    <div class="input-group flex-nowrap mb-3">
      <span class="input-group-text" style="width:8rem;" id="addon-wrapping">사용 내역 분류</span>
      <input type="text" id="category" name="category" class="form-control" placeholder="category" aria-label="category" aria-describedby="addon-wrapping">
    </div>
    <div class="input-group flex-nowrap mb-3">
      <span class="input-group-text" style="width:8rem;" id="addon-wrapping">사용 금액</span>
      <input type="number" id="amount" name="amount" class="form-control" placeholder="amount" aria-label="amount" aria-describedby="addon-wrapping">
    </div>
    <div class="input-group flex-nowrap mb-3">
      <span class="input-group-text" style="width:8rem;" id="addon-wrapping">사용 날짜</span>
      <input type="date" id="date" name="date" class="form-control" placeholder="date" aria-label="date" aria-describedby="addon-wrapping" value="{{ cur_date|date:"Y-m-d" }}">
    </div>
    <div class="input-group flex-nowrap">
      <input type="submit" class="form-control border-dark" placeholder="SUBMIT" aria-label="SUBMIT" aria-describedby="addon-wrapping">
    </div>
  </form>
{% endblock content %}