accounts/urls.py
from django.urls import path
from . import views

app_name = 'accounts'
urlpatterns = [
    path('login/', views.login, name='login'),
    path('logout/', views.logout, name='logout'),
    path('signup/', views.signup, name='signup'),
    path('delete/', views.delete, name='delete'),
    path('update/', views.update, name='update'),
    path('password/', views.change_password, name='change_password'),
    path('profile/<username>/', views.profile, name='profile'),
    path('<int:user_pk>/follow/', views.follow, name='follow'),
]

apps/urls.py
from django.urls import path
from . import views

app_name = 'apps'
urlpatterns = [
    path('throw/', views.throw, name='throw'),
    path('catch/', views.catch, name='catch'),
    path('lotto_create/', views.lotto_create, name='lotto_create'),
    path('lotto/', views.lotto, name='lotto'),
    path('apps/<int:num>/', views.detail, name='detail'),
    path('apps/<str:name>/', views.greeting, name='greeting'),
    path('todaydinner/', views.todaydinner, name='todaydinner'),
]

articles/urls.py
from django.urls import path
from . import views

app_name = 'articles'
urlpatterns = [
    path('', views.index, name='index'),
    path('<int:pk>/', views.detail, name='detail'),
    path('create/', views.create, name='create'),
    path('<int:pk>/delete/', views.delete, name='delete'),
    path('<int:pk>/update/', views.update, name='update'),
    path('<int:pk>/comments/', views.comments_create, name='comments_create'),
    path('<int:article_pk>/comments/<int:comment_pk>/delete/', views.comments_delete, name='comments_delete'),
    path('<int:article_pk>/likes/', views.likes, name='likes'),
    path('index-1/', views.index_1),
    path('index-2/', views.index_2),
    path('index-3/', views.index_3),
    path('index-4/', views.index_4),
]

firstpjt/urls.py
from django.contrib import admin
from django.urls import path, include
# WARNINGS: (urls.W005) URL namespace 'MayTwentyThird' isn't unique. You may not be able to reverse all URLs in this namespace
# https://comdoc.tistory.com/entry/URL-namespace-xxx-isnt-unique
from django.shortcuts import redirect
from django.conf import settings
from django.conf.urls.static import static

urlpatterns = [
    path('', include('mainpg.urls')),
    path('admin/', admin.site.urls),
    path('apps/', include('apps.urls')),
    path('MarchTwentyThird/', include('MarchTwentyThird.urls')),
    path('articles/', include('articles.urls')),
    path('todos/', include('todos.urls')),
    path('accountbooks/', include('accountbooks.urls')),
    path('accounts/', include('accounts.urls')),
    path('albums/', include('albums.urls')),
    path('reviews/', include('reviews.urls')),
    path('hospitals/', include('hospitals.urls')),
    path('__debug__/', include('debug_toolbar.urls')),
] + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

articles/models.py
from django.conf import settings
from django.db import models

# Create your models here.
class Article(models.Model):
    user = models.ForeignKey(settings.AUTH_USER_MODEL, on_delete=models.CASCADE)
    like_users = models.ManyToManyField(settings.AUTH_USER_MODEL, related_name='like_articles')
    title = models.CharField(max_length=80)
    content = models.TextField()
    image = models.ImageField(blank=True)
    created_at = models.DateTimeField(auto_now_add=True)
    updated_at = models.DateTimeField(auto_now=True)

class Comment(models.Model):
    article = models.ForeignKey(Article, on_delete=models.CASCADE)
    user = models.ForeignKey(settings.AUTH_USER_MODEL, on_delete=models.CASCADE)
    content = models.CharField(max_length=200)
    created_at = models.DateTimeField(auto_now_add=True)
    updated_at = models.DateTimeField(auto_now=True)

articles/forms.py
from django import forms
from .models import Article, Comment

class ArticleForm(forms.ModelForm):
    title = forms.CharField(
        label='제목',
        widget=forms.TextInput(
            attrs = {
                'class': 'my-title',
                'placeholder': 'Enter the title',
                'maxlength': 10,
            }
        ),
    )
    content = forms.CharField(
        label='내용',
        widget=forms.Textarea(
            attrs = {
                'class': 'my-content',
                'placeholder': 'Enter the content',
                'rows': 5,
                'cols': 50,
            }
        ),
        error_messages = {'required': '내용을 입력해주세요.'},
    )

    class Meta:
        model = Article
        fields = ('title', 'content',)

class CommentForm(forms.ModelForm):
    class Meta:
        model = Comment
        fields = ('content', )

articles/views.py
from django.shortcuts import render, redirect
from .models import Article, Comment
from .forms import ArticleForm, CommentForm
from django.contrib.auth.decorators import login_required
from django.db.models import Count
from django.http import JsonResponse

# Create your views here.
def index(request):
    articles = Article.objects.all()
    context = {
        'articles': articles,
    }
    return render(request, 'articles/index.html', context)

def detail(request, pk):
    article = Article.objects.get(pk=pk)
    comments = article.comment_set.all()
    comment_form = CommentForm()
    context = {
        'article': article,
        'comments': comments,
        'comment_form': comment_form,
    }
    return render(request, 'articles/detail.html', context)

@login_required
def comments_create(request, pk):
    article = Article.objects.get(pk=pk)
    comment_form = CommentForm(request.POST)
    if comment_form.is_valid():
        comment = comment_form.save(commit=False)
        comment.article = article
        comment.user = request.user
        comment.save()
        return redirect('articles:detail', article.pk)
    context = {
        'article': article,
        'comment_form': comment_form,
    }
    return render(request, 'articles/detail.html', context)

@login_required
def comments_delete(request, article_pk, comment_pk):
    comment = Comment.objects.get(pk=comment_pk)
    if request.user == comment.user:
        comment.delete()
    return redirect('articles:detail', article_pk)

@login_required
def create(request):
    if request.method == 'POST':
        form = ArticleForm(request.POST, request.FILES)
        if form.is_valid():
            article = form.save(commit=False)
            article.user = request.user
            article.save()
            return redirect('articles:detail', article.pk)
    else:
        form = ArticleForm()
    context = {
        'form': form,
    }
    return render(request, 'articles/create.html', context)

@login_required
def delete(request, pk):
    article = Article.objects.get(pk=pk)
    if request.user == article.user:
        article.delete()
    return redirect('articles:index')

@login_required
def update(request, pk):
    article = Article.objects.get(pk=pk)
    if request.user == article.user:
        if request.method == 'POST':
            form = ArticleForm(request.POST, request.FILES, instance=article)
            if form.is_valid():
                form.save()
                return redirect('articles:detail', article.pk)
        else:
            form = ArticleForm(instance=article)
    else:
        return redirect('articles:index')
    context = {
        'article': article,
        'form': form,
    }
    return render(request, 'articles/update.html', context)

@login_required
def likes(request, article_pk):
    article = Article.objects.get(pk=article_pk)
    if request.user in article.like_users.all():
        article.like_users.remove(request.user)
        is_liked = False
    else:
        article.like_users.add(request.user)
        is_liked = True
    context = {
        'is_liked': is_liked,
    }
    return JsonResponse(context)

# def likes(request, article_pk):
#     article = Article.objects.get(pk=article_pk)
#     if article.like_users.filter(pk=request.user.pk).exists():
#         article.like_users.remove(request.user)
#     else:
#         article.like_users.add(request.user)
#     return redirect('articles:index')

def index_1(request):
    articles = Article.objects.order_by('-pk')
    # articles = Article.objects.annotate(Count('comment')).order_by('-pk')
    context = {
        'articles': articles,
    }
    return render(request, 'articles/index_1.html', context)


def index_2(request):
    # articles = Article.objects.order_by('-pk')
    articles = Article.objects.select_related('user').order_by('-pk')
    context = {
        'articles': articles,
    }
    return render(request, 'articles/index_2.html', context)


def index_3(request):
    # articles = Article.objects.order_by('-pk')
    articles = Article.objects.prefetch_related('comment_set').order_by('-pk')
    context = {
        'articles': articles,
    }
    return render(request, 'articles/index_3.html', context)


from django.db.models import Prefetch


def index_4(request):
    articles = Article.objects.prefetch_related(
        Prefetch('comment_set', queryset=Comment.objects.select_related('user'))
    ).order_by('-pk')

    context = {
        'articles': articles,
    }
    return render(request, 'articles/index_4.html', context)

articles/templates/articles/create.html
{% extends 'base.html' %}

{% block style %}
  <style>
    body {
      margin: 20px;
    }
  </style>
{% endblock style %}
{% block content %}
  <h1>CREATE</h1>
  <form action="{% url 'articles:create' %}" method="POST" enctype="multipart/form-data">
    {% csrf_token %}
    {{ form.as_p }}
    <input type="submit" class="btn btn-secondary mb-2">
  </form>
  <a href="{% url 'articles:index' %}" class="btn btn-secondary">BACK</a>
{% endblock content %}

articles/templates/articles/detail.html
{% extends 'base.html' %}

{% block style %}
  <style>
    * {
      margin: 20px;
    }
  </style>
{% endblock style %}

{% block content %}
  <h1>DETAIL</h1>
  <h3>{{ article.pk }}번째 글</h3>
  <hr>
  <p>작성자: {{ article.user }}</p>
  <p>제목: {{ article.title }}</p>
  <p>내용: {{ article.content }}</p>
  <p>댓글 목록</p>
  <ul>
    {% for comment in comments %}
      <li>댓글 {{ comment.user }}: {{comment.content }}
        {% if request.user == comment.user %}
          <form action="{% url 'articles:comments_delete' article.pk comment.pk %}" method="POST">
            {% csrf_token %}
            <input type="submit" value="DELETE" class="btn btn-dark"> 
          </form>
        {% endif %}
      </li>
    {% empty %}
      <p>댓글이 없습니다.</p>
    {% endfor %}
  </ul>
  <p>작성 시각: {{ article.created_at }}</p>
  <p>수정 시각: {{ article.updated_at }}</p>
  {% if article.image %}
    <img src="{{ article.image.url }}" alt="img">
  {% endif %}
  <form action="{% url 'articles:comments_create' article.pk %}" method = "POST">
    {% csrf_token %}
    {{ comment_form }}
    <input type="submit" class="btn btn-dark">
  </form>
  <hr>
  {% if request.user == article.user %}
    <a href="{% url 'articles:update' article.pk %}" class="btn btn-secondary">EDIT</a>
    <form action="{% url 'articles:delete' article.pk %}" method="POST">
      {% csrf_token %}
      <input type="submit" value="DELETE" class="btn btn-secondary">
    </form>
  {% endif %}
  <a href="{% url 'articles:index' %}" class="btn btn-secondary">BACK</a>

{% endblock content %}

articles/templates/articles/edit.html
{% extends 'base.html' %}

{% block style %}
  <style>
    body {
      margin: 20px;
    }
  </style>
{% endblock style %}

{% block content %}
  <h1>Articles EDIT</h1>
  <form action="{% url 'articles:update' article.pk %}" method="POST">
    {% csrf_token %}
    <div>
      <label for="title">Title: </label>
      <input type="text" name="title" id="title" value="{{ article.title }}">
    </div>
    <div>
      <label for="content">Content: </label>
      <input type="text" name="content" id="content" value="{{ article.content }}">
    </div>
    <input type="submit">
  </form>
  <hr>
  <a href="{% url 'articles:index' %}">[BACK]</a>
{% endblock content %}

articles/templates/articles/index.html
{% extends 'base.html' %}

{% block style %}
  <style>
    * {
      margin: 20px;
    }
  </style>
{% endblock style %}
{% block content %}
  <h1>ARTICLES</h1>
  <p>{{ articles }}</p>
  <hr>
  <a href="{% url 'accounts:profile' user.username %}">내 프로필</a>
  <p>새로운 입력:<a href="{% url 'articles:create' %}">NEW</a></p>
  {% for article in articles %}
  <div class="d-flex gap-2">
    <p>{{ article.pk }}. <a href="{% url 'accounts:profile' article.user.username %}">{{ article.user }}</a> : <a href="{% url 'articles:detail' article.pk %}">{{ article.title }}</a></p>
    <form class="like-forms" data-article-id="{{ article.pk }}">
      {% csrf_token %}
      {% if request.user in article.like_users.all %}
        <input type="submit" value="좋아요 취소" id="like-{{ article.pk }}">
      {% else %}
        <input type="submit" value="좋아요" id="like-{{ article.pk }}">
      {% endif %}
    </form>
  </div>
  {% endfor %}
  {% load static %}
  <img src="{% static 'articles/E8hijkMVEAI4dqV.jpg' %}" alt="img">
  <img src="{% static 'CoD9h2VUkAAY1Sq.jpeg' %}" alt="img">
  <script src="https://cdn.jsdelivr.net/npm/axios/dist/axios.min.js"></script>
  <script>
    const forms = document.querySelectorAll('.like-forms')
    const csrftoken = document.querySelector('[name=csrfmiddlewaretoken]').value
    forms.forEach((form) => {
      form.addEventListener('submit', function (event) {
        event.preventDefault()
        const articleId = event.target.dataset.articleId
        axios({
          method: 'post',
          url: `http://127.0.0.1:8000/articles/${articleId}/likes/`,
          headers: {'X-CSRFToken': csrftoken},
        })
        .then((response) => {
          const isLiked = response.data.is_liked
          const likeBtn = document.querySelector(`#like-${articleId}`)
          if (isLiked === true) {
            likeBtn.value = '좋아요 취소'
          } else {
            likeBtn.value = '좋아요'
          }
        })
        .catch((error) => {
          console.log(error.response)
        })
      })
    })
  </script>
{% endblock content %}

articles/templates/articles/index_1.html
{% extends 'base.html' %}

<!-- index_1.html -->
{% block style %}
  <style>
    body {
      margin: 20px;
    }
  </style>
{% endblock style %}
{% block content %}
  <h1>Articles</h1>
  {% for article in articles %}
    <p>제목 : {{ article.title }}</p>
    <p>댓글 갯수 : {{ article.comment__count }}</p>
    <hr>
  {% endfor %}
{% endblock content %}

articles/templates/articles/index_2.html
{% extends 'base.html' %}
{% block style %}
  <style>
    body {
      margin: 20px;
    }
  </style>
{% endblock style %}
{% block content %}
  <h1>Articles</h1>
{% for article in articles %}
  <h3>작성자 : {{ article.user.username }}</h3>
  <p>제목 : {{ article.title }}</p>
  <hr>
{% endfor %}
{% endblock content %}

articles/templates/articles/index_3.html
{% extends 'base.html' %}
{% block style %}
  <style>
    body {
      margin: 20px;
    }
  </style>
{% endblock style %}
{% block content %}
  <h1>Articles</h1>
  {% for article in articles %}
    <p>제목 : {{ article.title }}</p>
    <p>댓글 목록</p>
    {% for comment in article.comment_set.all %}
      <p>{{ comment.content }}</p>
    {% endfor %}
    <hr>
  {% endfor %}
{% endblock content %}

articles/templates/articles/index_4.html
{% extends 'base.html' %}
{% block style %}
  <style>
    body {
      margin: 20px;
    }
  </style>
{% endblock style %}
{% block content %}
  <h1>Articles</h1>
{% for article in articles %}
  <p>제목 : {{ article.title }}</p>
  <p>댓글 목록</p>
  {% for comment in article.comment_set.all %}
    <p>{{ comment.user.username }} : {{ comment.content }}</p>
  {% endfor %}
  <hr>
{% endfor %}
{% endblock content %}

articles/templates/articles/today_dinner.html
{% extends 'base.html' %}

{% block style %}
  <style>
    body {
      margin: 20px;
    }

    span {
      color: crimson;
    }
  </style>
{% endblock style %}

{% block content %}
  <h1>오늘의 추천 메뉴는 <span>{{ picked }}</span>입니다.</h1>
  <a href="{% url 'articles:today_dinner' %}">dinner</a>
{% endblock content %}

articles/templates/articles/update.html
{% extends 'base.html' %}

{% block style %}
  <style>
    body {
      margin: 20px;
    }
  </style>
{% endblock style %}

{% block content %}
  <h1>Articles EDIT</h1>
  <form action="{% url 'articles:update' article.pk %}" method="POST" enctype="multipart/form-data">
    {% csrf_token %}
    {{ form.as_p }}
    <input type="submit">
  </form>
  <hr>
  <a href="{% url 'articles:index' %}">[BACK]</a>
{% endblock content %}